# Generated by Django 6.1.1 on 2026-09-10 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storefront_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=80)),
                ('region', models.CharField(max_length=80)),
                ('is_public', models.BooleanField(default=False, help_text='Storefront is visible to consumers only when public.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='farmer_farm_user_id_2927e8_idx')],
            },
        ),
    ]
